### ISSUE TITLE
Basic CRUD

### ISSUE THREAD

**Issue by felansu** [Qr-Bibliokode/QRBWS#1]
Build a simple CRUD for all entities.

**Comment by aparecidapires** [comment]
Funcionalidades:

HolidayController :
• Feriado - Definir quantidade máxima de caracteres; Está aceitando números e não deveria; 

EmployeeController : 
Email  - Definir quantidade máxima de caracteres para o campo;
• Phone - Definir máscara para o campo. está aceitando qualquer tipo de  string; definir quantidade máxima de caracteres;
• Code – Foi definido a quantidade de caracteres (5).  Aceita números e caracteres, mas poderia flexionar mais na quantidade de caracteres.

CategoryController: 
• Description – Definir quantidade máxima de caracteres; Verificar se comporta números;
• Adicionar Book - ????
Obs: Assim que eu crio uma nova categoria, aparece a opção de Editar e Remover e é possível fazer as duas coisas, mas depois que clico para listar, não aparece mais opção de excluir ou editar. Não aparece o sublinhado do link como nos outros cadastros.
Obs: Quando vou  cadastrar uma categoria aparece a opção de Adicionar book, mas se eu selecionar vou para o cadastro de livro e perco o cadastro de categoria que eu estava fazendo.

StatusController:
• Description – Definir quantidade máxima de caracteres, verificar se comporta números e a quantidade de cadastros para o status (Disponível/Indisponível).

LanguageController:
• Definir quantidade máxima de caracteres e verificar se comporta números.

StudentController:
• Name – Já está com limite de caracteres definido, Permite inserção de números
• Email - Definir a quantidade máxima de caracteres;
• Phone – Definir quantidade de caracteres (e máscara);
• Enrollment – Aceita letras e números. Obs: A matrícula precisa aceitar letras e números mesmo.
BookController
• ISBN – Aceita de 10 a 15 caracteres, mas o total é de 17 espaços.  Obs: Está aceitando qualquer tipo de caracter;
- Formato para nova numeração:
  ISBN 978 - 85 - 333 - 0227 - 3
  http://www.isbn.bn.br/website/como-e-onde-utilizar-o-isbn

• Títle – Aceita caracteres de 5 a 450. Talvez exista um título com apenas 2 ou 3 caracteres;
• Pages – Fazer validação páginas negativas;
• Cover – Não consegui inserir imagem. Fiz teste com jpg, png, docx, doc e pdf e aparece o nome do arquivo no cover, mas quando clica em criar, aparece uma mensagem de erro : For input string: "aula3.pdf e o nome do arquivo no Cover desaparece, e aparece nenhum arquivo selecionado;
• Adicionar comentário 
• Obs: Ao inserir o comentário, fui para a página de comentário, preenchi o comentário, mas perdi o cadastro de livro que eu estava fazendo...
• Existe a opção de escolher autor para o livro, mas nem todos registraram. Quando voltei para editar consegui inserir o autor na edição.

ComentController:
• Avaliation – Deve ser estipulado um valor limite; 

AuthorController: 
• Books – Existe a opção de escolher um livro, mas somente os primeiros registraram o livro. Quando voltei na edição consegui registrar o livro no autor.
Obs: O autor tem livro e o livro tem autor. Se tentar excluir qualquer um dos dois, aparece a mensagem de javaScript confirmando o desejo de exclusão e mesmo confirmando, aparece a seguinte mensagem de erro: An error has occurred. Para sair tem que deletar o caminho que complementa o localhost:8080. 
Obs: Ao cadastrar o autor Cora Coralina, embora estivessem aparecendo dois livros, no cadastro não apareceu livro...

UserControler:
Obs: Ao invés de aparecer o id do status, ficaria mais claro se aparecesse o estado do livro.(Obs: Não entendi o status no usuário ! Status não é a condição disponível/indisponível do libro ?)

  Sugestões: 
O cadastro do categoria não precisa ter o livro. No cadastro do livro é associada a categoria.
O cadastro do autor não precisa ter o livro. No cadastro do livro é associado o autor.

– Não entendi o adicionar comentário dentro do cadastro do livro. (Não seria o usuário que insere comentário ?)

**Comment by aparecidapires** [comment]
Primeiro teste

**Comment by felansu** [comment]
- [x] **Holiday:** Segundo a lista de feriados no brasil (http://www.calendario-365.com.br/feriados/2015.html), o maior tem 40 caracteres. Limitei a **description** pra 45 e não são permitidos números.
- [x] **Employee:** As propriedades **email e phone** são da entidade Person, foi definido um maxSize de 254 para elas. Por enquanto foi definido um maxSize de 5 para String **code**.
- [x] **Category:** Pra Description foi definido um maxSize de 254. Solucionado problema que não deixava editar a category. Agora só o book que tem category.
- [x] **Status:** Pra Description foi definido um maxSize de 45. Fiquei na dúvida entre enum ou entidade. Porém acho que estes estados podem ser utilizados na aplicação em geral, estados do livro, do usuário, da devolução, etc..
- [x] **Language:** Pra Description foi definido um maxSize de 45. 
- [x] **Student:**  Name só permite números, Email quantidade maxSize de 254, Phone maxSize de 15 (padrão mundial), a mascara será definida no front-end (angular).
- [x] **Book:**  ISBN alterado para maxSize 17. Títle alterado para maxSize 254. Acrescentada validação de páginas, agora só aceita números positivos. Cover será feito mais na frente.
- [x] **Adicionar comentário:**  Não precisa preocupar com o link que aparece na página do Book pra adicionar um comentário, isto é gerado automaticamente pelo grails, porem quando passemos pro front com angular, esta opção será removida.
- [x] **Coment:**  Agora avaliation não pode ser negativa e um maxSize de 5. Description maxSize de 500
- [x] **Author:**  Resolvido os problemas, agora author apenas é um atributo do libro, não fazia sentido que a entidade author tivesse livros... Agora pode deletar autores que não irá interferir em nada no livro.
- [x] **User:**  Depois no front a gente decide o que iremos mostrar, os status são referentes a qualquer objeto da aplicação. Que acha disso ?

Agora leio suas sugestões, foi exatamente isso que fiz :dancer: 

> Não entendi o adicionar comentário dentro do cadastro do livro. (Não seria o usuário que insere > > > comentário ?

Sim, o grails gera pra facilitar seus testes.

**Nota:** Ao iniciar a aplicação é salva uma categoria, language e dois estados (para facilitar os testes)

**Comment by aparecidapires** [comment]
Test Version-2

Holiday - É possível criar um novo Holiday com apenas uma palavra. Ao fazer o cadastro contendo espaço entre palavras, aparece a seguinte mensagem: "É preciso que o formato corresponda ao exigido. 

Book 
- Autor - Deveria aparecer uma forma de selecionar um autor já cadastrado anteriormente. Até aparece um link Adicionar Autor, mas leva para o cadastro de autor e se perde o cadastro do livro.
  *Comentario - Quem vai fazer o comentário é o usuário, depois de feito o cadastro do livro. Também perde o cadastro do livro ao clicar em comentário, sendo redirecionado para essa funcionalidade.

**Comment by felansu** [comment]
Foi refatorada a classe Holiday, agora não permite números na descrição. A descrição agora é única.
Por enquanto não preocupe com as opções da página, isso será tratado no front com angular.
